[config]
schemaVersion = "0.0.1"

[package]
namespace = "ykysnk"
name = "BepinExUtils_LuaLoader"
versionNumber = "0.0.1" # will be replaced
description = "Lua Loader for BepInEx"
websiteUrl = "https://github.com/T2PeNBiX99wcoxKv3A4g/BepInEx-Utils.LuaLoader"
containsNsfwContent = false
[package.dependencies]
ykysnk-BepinExUtils = "1.0.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["hollow-knight-silksong", ]
[publish.categories]
hollow-knight-silksong = ["mods", "tools", ]
